services:
  postgres:
    image: postgres:latest
    container_name: postgres-approval
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql
    env_file:
      - ./app.env
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin-approval
    env_file:
      - ./app.env
    ports:
      - '5050:80'
  redis:
    image: redis:alpine
    container_name: redis-approval
    ports:
    - "6380:6379"
    volumes:
      - redisDB:/data
volumes:
  redisDB:
  progresDB: